"""empty message

Revision ID: 980e9802c6a7
Revises: 4c63ce32b217
Create Date: 2021-02-22 21:54:44.572139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980e9802c6a7'
down_revision = '4c63ce32b217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
